### ISSUE TITLE
Harmonize data types

### ISSUE THREAD

**Issue by linusonline** [AMSP-04/NETN-Aggregate#2]
See issue https://github.com/AMSP-04/NETN-BASE/issues/1

**Comment by linusonline** [comment]
Propose:

- Remove data type PercentageUint32 (move to NETN-BASE)
- Remove data type QuantityFloat64 (use NETN-BASE::QuantityFloat64)
- For attribute Mounted in class NETN_Aggregate, use data type RPR-BASE::PercentFloat32
- Remove data type FacingDegreesFloat32 (use NETN-BASE::DirectionDegreesFloat32)
- Change semantics of field Facing in data type EntityStruct to mean relative to true north instead of relative to aggregate's orientation.

**Comment by LennartOlsson** [comment]
NETN_Aggregate.Mounted is now a QuantityFloat64, changing this will affect the encoding/decoding for existing applications (MASA Sword), my propose: No change. The semantics is unclear for the attribute, add value range [0..100] in the semantics.

Changing the field Facing in data type EntityStruct to true north will result that it has to be recalculated every time the aggregate change direction, e.g. when a aggregate ship with embarked tanks change direction, the facing for all embarked tanks has to be recalculated, my propose: No change.

**Comment by linusonline** [comment]
Proposed changes now pushed. Please reopen this issue if you disagree with the changes.

**Comment by lofstrandbjorn** [comment]
Updated release notes with the following

* Replaced datatype `PercentageUint32` with `PercentUnsignedInteger32`
* Removed datatype `PercentageUint32`
* Moved datatype `QuantityFloat64` to NETN-BASE
* Changed datatype of `NETN_Aggregate` object class attribute `Mounted` to `PercentFloat64`
* Replaced datatype `FacingDegreesFloat32` with `DirectionDegreesFloat32`
* Removed datatype `FacingDegreesFloat32`
* Replaced datatype `TimeSecInt64` with `EpochTimeSecInt64`
