### ISSUE TITLE
Attribute Footprint missing defined datatype

### ISSUE THREAD

**Issue by LennartOlsson** [AMSP-04/NETN-Aggregate#4]
ArrayOfWorldLocationStruct3 is no more, should be GeocentricPolygon from NETN-BASE

**Comment by LennartOlsson** [comment]
Fixed

**Comment by lofstrandbjorn** [comment]
* Changed datatype of `NETN_Aggregate` object class attribute `Footprint` from `ArrayOfWorldLocationStruct3` to `GeocentricPolygon `
